terms:
- id: Age_7-8
  term: "Age 7-8 (Year 3)"
- id: Age_8-9
  term: "Age 8-9 (Year 4)"
- id: Age_9-10
  term: "Age 9-10 (Year 5)"
- id: Age_10-11
  term: "Age 10-11 (Year 6)"
- id: Age_11-12
  term: "Age 11-12 (Year 7)"
- id: Age_12-13
  term: "Age 12-13 (Year 8)"
- id: Age_13-14
  term: "Age 13-14 (Year 9)"
- id: Age_14-15
  term: "Age 14-15 (Year 10)"
- id: Age_15-16
  term: "Age 15-16 (Year 11)"
- id: Age_16-17
  term: "Age 16-17 (Year 12)"
- id: Age_17-18
  term: "Age 17-18 (Year 13)"
